In [1]:
import mysql.connector


cnx = mysql.connector.connect(user='root', password='AlumnaAdalab',
                              host='127.0.0.1',
                              database='Northwind')

print(cnx)

<mysql.connector.connection_cext.CMySQLConnection object at 0x0000026E006BD930>

In [2]:
#EJERCICIO1: MOSTRAR BBDD QUE TENEMOS EN EL SERVIDOR

import mysql.connector

mydb = mysql.connector.connect(
                  user='root', password='AlumnaAdalab',
                  host='127.0.0.1',
                  database='Northwind')

mycursor = mydb.cursor()

mycursor.execute("SHOW DATABASES")

for x in mycursor:
  print(x)

('information_schema',)
('leccion-1-sql',)
('leccion-10-sql',)
('leccion-11-sql',)
('leccion-12-sql',)
('leccion-13-sql',)
('leccion-14-sql',)
('leccion-2-sql',)
('leccion-3-sql',)
('leccion-4-sql',)
('leccion-5-sql',)
('leccion-6-sql',)
('leccion-7-sql',)
('leccion-8-sql',)
('leccion-9-sql',)
('mysql',)
('northwind',)
('performance_schema',)
('sakila',)
('sys',)
('tienda',)
('world',)
('zapatitos',)

In [3]:
#EJERCICIO 2: MOSTRAR EL NOMBRE DE LAS TABLAS DE LA BBDD EN UNA LISTA

mycursor.execute("SHOW TABLES")

tablas = []
    
for x in mycursor:
    tablas.append(x)
    
print(tablas)

[('categories',), ('customer_customer_demo',), ('customer_demographics',), ('customers',), ('employee_territories',), ('employees',), ('order_details',), ('orders',), ('products',), ('region',), ('shippers',), ('suppliers',), ('territories',)]

In [4]:
#EJERCICIO 3: MOSTRAR COLUMNAS QUE TIENE CADA UNA DE LAS TABLAS. 


mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="AlumnaAdalab",
  database="INFORMATION_SCHEMA"
)

mycursor = mydb.cursor()

mycursor.execute("SELECT COLUMN_NAME FROM COLUMNS WHERE TABLE_SCHEMA = 'Northwind'")


columnas = []
for x in mycursor:
   columnas.extend(x)
  
print(columnas)

['category_id', 'category_name', 'description', 'picture', 'customer_id', 'customertype_id', 'customer_desc', 'customer_type_id', 'address', 'city', 'company_name', 'contact_name', 'contact_title', 'country', 'customer_id', 'fax', 'phone', 'postal_code', 'region', 'employee_id', 'territory_id', 'address', 'birth_date', 'city', 'country', 'employee_id', 'extension', 'first_name', 'hire_date', 'home_phone', 'last_name', 'notes', 'photo', 'photo_path', 'postal_code', 'region', 'reports_to', 'title', 'title_of_courtesy', 'discount', 'order_id', 'product_id', 'quantity', 'unit_price', 'customer_id', 'employee_id', 'freight', 'order_date', 'order_id', 'required_date', 'ship_address', 'ship_city', 'ship_country', 'ship_name', 'ship_postal_code', 'ship_region', 'ship_via', 'shipped_date', 'category_id', 'discontinued', 'product_id', 'product_name', 'quantity_per_unit', 'reorder_level', 'supplier_id', 'unit_price', 'units_in_stock', 'units_on_order', 'region_description', 'region_id', 'company_name', 'phone', 'shipper_id', 'adress', 'city', 'company_name', 'contact_name', 'contact_title', 'country', 'fax', 'home_page', 'phone', 'postal_code', 'region', 'supplier_id', 'region_id', 'territory_description', 'territory_id']

In [5]:
#EJERCICIO 4: QUERIES FACILITAS

    #Extraed el primer pedido donde se ha gastado m√°s. Devolved el id del pedido y la cantidad gastada.


mydb = mysql.connector.connect(
                  user='root', password='AlumnaAdalab',
                  host='127.0.0.1',
                  database='Northwind')

mycursor = mydb.cursor()

mycursor.execute("SELECT order_id, MAX(unit_price * quantity) AS Cantidad_Gastada FROM order_details")

for x in mycursor:
    print(x)

(10248, 15810.0)

In [6]:
    # Devuelve la misma query que en el anterior ejercicio, pero en este caso devuelve todos los resultados.

mydb = mysql.connector.connect(
                  user='root', password='AlumnaAdalab',
                  host='127.0.0.1',
                  database='Northwind')

mycursor = mydb.cursor()

mycursor.execute("SELECT order_id, MAX(unit_price * quantity) AS Cantidad_Gastada FROM order_details GROUP BY order_id ORDER BY Cantidad_gastada DESC")

for x in mycursor:
 print(x)

(10865, 15810.0)
(10981, 15810.0)
(10353, 10540.0)
(10417, 10540.0)
(10889, 10540.0)
(10424, 10329.2)
(10897, 9903.2)
(10372, 8432.0)
(10540, 7905.0)
(10816, 7905.0)
(10817, 7905.0)
(10912, 7427.400000000001)
(11030, 7427.400000000001)
(11032, 6587.5)
(10776, 6360.0)
(10479, 6324.0)
(10993, 6189.5)
(11017, 6050.0)
(10515, 5268.0)
(10691, 4951.6)
(10687, 4850.0)
(10510, 4456.4400000000005)
(10666, 4456.4400000000005)
(11072, 4322.5)
(10329, 4216.0)
(10351, 4216.0)
(10953, 4050.0)
(10518, 3952.5)
(10616, 3952.5)
(10672, 3952.5)
(10633, 3944.0)
(10711, 3935.9999999999995)
(10607, 3900.0)
(10678, 3800.0)
(10360, 3465.0)
(10595, 3420.0)
(10895, 3400.0)
(11008, 3192.0)
(10514, 3159.0)
(10634, 3125.0)
(10854, 3100.0)
(10267, 3080.0)
(10430, 3080.0)
(11064, 3003.0)
(10893, 2970.96)
(10949, 2958.0)
(10324, 2808.0)
(10524, 2760.0)
(10316, 2758.0)
(10841, 2750.0)
(10688, 2736.0)
(10694, 2700.0)
(10561, 2650.0)
(10490, 2640.0)
(10805, 2635.0)
(10252, 2592.0)
(10549, 2544.0)
(10588, 2500.0)
(10629, 2475.8)
(10787, 2475.8)
(10801, 2475.8)
(10305, 2475.0)
(10745, 2475.0)
(10852, 2465.0)
(10605, 2380.0)
(10440, 2376.0)
(10764, 2340.0)
(11021, 2332.0)
(10701, 2310.0)
(10851, 2310.0)
(10398, 2304.0)
(10451, 2304.0)
(11033, 2296.0)
(10402, 2281.5)
(10570, 2280.0)
(10637, 2280.0)
(10762, 2280.0)
(10344, 2240.0)
(10345, 2240.0)
(10772, 2228.2200000000003)
(10567, 2200.0)
(10823, 2200.0)
(10892, 2200.0)
(10598, 2195.0)
(11053, 2187.5)
(10339, 2184.0)
(10359, 2176.0)
(10612, 2170.0)
(10886, 2170.0)
(10401, 2128.0)
(10948, 2120.0)
(10831, 2108.0)
(10638, 2088.0)
(10400, 2079.0)
(10836, 2040.0)
(10335, 2035.1999999999998)
(10332, 2000.0)
(10369, 1980.0)
(10546, 1972.0)
(10988, 1972.0)
(10601, 1925.0)
(10703, 1925.0)
(10990, 1881.0)
(10789, 1875.0)
(10658, 1870.0)
(10395, 1834.0)
(10384, 1814.3999999999999)
(10894, 1800.0)
(10987, 1800.0)
(11001, 1800.0)
(10465, 1782.0)
(10760, 1756.0)
(10921, 1756.0)
(10441, 1755.0)
(10618, 1750.0)
(10393, 1743.0)
(10941, 1739.9999999999998)
(10791, 1733.0600000000002)
(10971, 1733.0600000000002)
(10904, 1725.5)
(10657, 1710.0)
(10593, 1701.0)
(10660, 1701.0)
(10742, 1700.0)
(11056, 1700.0)
(10249, 1696.0)
(10765, 1684.0)
(10938, 1666.0)
(11068, 1656.0)
(10617, 1650.0)
(11036, 1650.0)
(10861, 1638.0)
(10419, 1632.0)
(10503, 1627.5)
(10667, 1620.0)
(10878, 1620.0)
(10991, 1620.0)
(10513, 1600.0)
(10709, 1600.0)
(10997, 1600.0)
(10845, 1596.0)
(10731, 1590.0)
(10802, 1590.0)
(10457, 1584.0)
(10286, 1576.0)
(10413, 1576.0)
(10516, 1562.5)
(10838, 1562.5)
(10877, 1562.5)
(10431, 1560.0)
(10530, 1560.0)
(10847, 1560.0)
(10420, 1552.0)
(10452, 1550.0)
(10979, 1536.5)
(10406, 1528.8)
(10519, 1520.0)
(10555, 1520.0)
(10470, 1500.0)
(10511, 1500.0)
(10361, 1496.0)
(10698, 1485.48)
(10290, 1485.0)
(10250, 1484.0)
(10757, 1479.0)
(10340, 1472.0)
(10392, 1440.0)
(10746, 1440.0)
(10812, 1392.0)
(10382, 1386.0)
(11023, 1380.0)
(11052, 1380.0)
(10408, 1379.0)
(10449, 1379.0)
(10750, 1375.0)
(10799, 1375.0)
(10718, 1368.0)
(10924, 1368.0)
(10795, 1365.0)
(10962, 1350.0)
(10343, 1330.0)
(10255, 1320.0)
(10298, 1320.0)
(10488, 1320.0)
(11028, 1320.0)
(10783, 1317.5)
(10964, 1317.5)
(11041, 1317.0)
(10756, 1312.5)
(10455, 1310.0)
(10292, 1296.0)
(10700, 1290.0)
(11012, 1290.0)
(10773, 1287.0)
(11045, 1272.0)
(10645, 1250.0)
(10871, 1250.0)
(10302, 1248.0)
(10330, 1245.0)
(10263, 1242.0)
(10583, 1237.9)
(10857, 1237.9)
(11007, 1237.9)
(10429, 1228.5)
(10436, 1216.0)
(10523, 1215.0)
(10986, 1215.0)
(10786, 1200.0)
(11039, 1200.0)
(10536, 1190.0)
(11059, 1190.0)
(10686, 1170.0)
(10796, 1163.75)
(10461, 1152.0)
(10526, 1140.0)
(10543, 1140.0)
(10547, 1140.0)
(10712, 1140.0)
(10755, 1140.0)
(10820, 1140.0)
(10968, 1140.0)
(10566, 1125.0)
(10346, 1123.2)
(10985, 1120.0)
(10804, 1116.0)
(10325, 1112.0)
(10459, 1112.0)
(10258, 1105.0)
(10641, 1104.0)
(10706, 1104.0)
(10527, 1100.0)
(10533, 1100.0)
(10930, 1097.5)
(10458, 1092.0)
(10481, 1088.0)
(10693, 1080.0)
(10747, 1080.0)
(10918, 1080.0)
(10961, 1080.0)
(11022, 1080.0)
(11035, 1080.0)
(11024, 1075.0)
(10608, 1064.0)
(10748, 1064.0)
(10486, 1060.0)
(10558, 1060.0)
(10663, 1060.0)
(10665, 1060.0)
(10995, 1060.0)
(11055, 1060.0)
(10541, 1054.0)
(10596, 1053.6)
(10714, 1053.0)
(10535, 1050.0)
(10766, 1050.0)
(10800, 1050.0)
(10388, 1048.0)
(10713, 1045.0)
(10575, 1044.0)
(10784, 1044.0)
(10866, 1035.6)
(11027, 1035.3)
(10396, 1032.0)
(10314, 1024.0)
(10684, 1020.0)
(10830, 1020.0)
(10603, 1008.0)
(10989, 1000.0)
(10557, 997.5)
(10859, 997.5)
(10834, 990.32)
(10268, 990.0)
(10994, 990.0)
(10554, 986.0)
(10779, 986.0)
(10872, 986.0)
(10721, 972.5)
(10522, 960.0)
(11002, 960.0)
(10984, 959.75)
(10283, 952.0)
(10285, 943.1999999999999)
(10677, 936.9)
(10265, 936.0)
(10368, 931.0)
(10681, 931.0)
(10644, 920.0)
(10814, 920.0)
(10270, 919.9999999999999)
(10572, 919.9999999999999)
(10744, 919.9999999999999)
(10418, 912.0)
(10464, 912.0)
(10494, 912.0)
(10499, 912.0)
(10649, 912.0)
(10733, 912.0)
(10855, 912.0)
(10976, 912.0)
(10717, 900.0)
(10729, 900.0)
(10808, 900.0)
(11050, 900.0)
(10312, 883.1999999999999)
(10273, 882.0)
(10423, 880.0)
(10692, 878.0)
(10977, 878.0)
(10257, 877.5)
(10680, 872.5)
(10297, 864.0)
(10364, 864.0)
(10373, 860.0)
(10880, 855.0)
(10933, 855.0)
(10433, 851.1999999999999)
(10774, 850.0)
(10362, 848.0)
(10965, 848.0)
(10736, 842.0)
(10327, 840.0)
(10619, 840.0)
(10635, 840.0)
(10868, 840.0)
(10556, 835.1999999999999)
(10803, 825.0)
(10835, 825.0)
(10573, 819.9999999999999)
(10650, 819.9999999999999)
(10442, 816.0)
(10475, 816.0)
(10954, 816.0)
(11031, 810.0)
(10829, 800.0)
(10967, 800.0)
(10978, 800.0)
(10370, 798.0)
(10884, 798.0)
(10999, 795.0)
(10389, 788.0)
(10260, 780.0)
(10590, 780.0)
(10696, 780.0)
(10707, 780.0)
(10727, 780.0)
(10551, 778.0)
(10751, 776.7)
(10957, 776.7)
(10946, 775.0)
(10342, 768.0)
(10397, 763.1999999999999)
(10472, 763.1999999999999)
(10690, 760.0)
(10781, 760.0)
(10790, 760.0)
(11018, 760.0)
(11029, 760.0)
(11046, 760.0)
(10670, 750.0)
(10719, 750.0)
(10734, 750.0)
(10404, 747.0)
(10421, 747.0)
(10487, 747.0)
(10357, 744.0)
(10664, 744.0)
(11020, 744.0)
(10624, 742.74)
(10560, 739.5)
(10627, 739.5)
(10769, 739.5)
(10309, 736.0)
(11063, 736.0)
(10844, 735.0)
(10537, 730.8)
(10277, 728.0)
(10377, 728.0)
(10347, 720.0)
(10471, 720.0)
(10485, 720.0)
(10640, 720.0)
(10869, 720.0)
(10902, 720.0)
(11070, 720.0)
(10403, 714.0)
(11058, 714.0)
(10504, 712.5)
(10410, 704.0)
(10675, 697.5)
(10337, 695.0)
(10497, 695.0)
(10932, 690.1999999999999)
(10507, 690.0)
(10333, 688.0)
(10643, 684.0)
(10944, 684.0)
(10626, 680.0)
(10653, 680.0)
(10328, 672.0)
(10492, 672.0)
(10272, 667.2)
(10390, 667.2)
(10876, 665.0)
(10278, 660.0)
(10679, 660.0)
(10913, 660.0)
(10825, 656.0)
(10474, 655.1999999999999)
(10427, 651.0)
(10715, 651.0)
(10661, 649.25)
(10552, 648.0)
(10646, 645.0)
(10901, 645.0)
(11038, 645.0)
(10848, 640.5)
(11047, 640.5)
(10253, 640.0)
(10818, 640.0)
(10975, 640.0)
(10580, 631.5)
(10630, 630.0)
(10689, 630.0)
(10740, 630.0)
(10584, 625.0)
(10722, 625.0)
(10768, 625.0)
(10853, 625.0)
(10758, 624.6)
(10338, 624.0)
(10564, 624.0)
(10411, 620.0)
(10685, 620.0)
(10301, 608.0)
(10383, 608.0)
(10469, 608.0)
(10896, 608.0)
(10293, 600.0)
(10399, 600.0)
(10659, 600.0)
(10833, 600.0)
(10908, 600.0)
(10929, 600.0)
(10982, 600.0)
(11010, 600.0)
(10565, 598.5)
(10966, 591.5999999999999)
(11044, 591.5999999999999)
(10303, 588.0)
(10447, 588.0)
(10890, 585.0)
(10922, 585.0)
(10931, 585.0)
(10356, 576.0)
(10294, 571.1999999999999)
(10525, 570.0)
(10632, 570.0)
(10642, 570.0)
(10669, 570.0)
(10735, 570.0)
(10749, 570.0)
(10936, 570.0)
(10849, 562.14)
(10379, 561.6)
(10463, 560.0)
(10939, 560.0)
(10942, 560.0)
(10996, 560.0)
(10269, 556.0)
(10287, 556.0)
(10468, 552.0)
(10811, 552.0)
(10636, 550.0)
(10726, 550.0)
(11000, 550.0)
(11005, 550.0)
(10656, 544.6)
(10284, 544.0)
(10385, 544.0)
(10569, 540.0)
(10623, 540.0)
(10914, 537.5)
(10264, 532.0)
(11011, 530.0)
(11026, 530.0)
(10387, 528.0)
(10480, 528.0)
(10828, 527.0)
(10780, 525.0)
(10862, 525.0)
(11048, 525.0)
(10380, 524.0)
(10839, 522.0)
(10350, 518.4)
(10320, 516.0)
(10611, 510.0)
(10728, 510.0)
(11061, 510.0)
(10319, 509.59999999999997)
(10407, 504.0)
(10553, 504.0)
(10983, 504.0)
(10639, 500.0)
(10934, 500.0)
(11076, 500.0)
(10668, 498.75)
(10450, 496.0)
(10478, 496.0)
(10724, 496.0)
(10562, 493.0)
(10574, 493.0)
(10599, 493.0)
(10606, 493.0)
(10671, 493.0)
(10563, 490.0)
(10761, 490.0)
(11066, 490.0)
(10304, 480.0)
(10925, 475.0)
(10723, 468.45)
(10279, 468.0)
(10911, 468.0)
(10827, 465.0)
(10846, 462.0)
(10923, 460.0)
(10788, 459.99999999999994)
(10837, 459.99999999999994)
(10439, 456.0)
(11077, 456.0)
(10600, 450.0)
(10628, 450.0)
(10697, 450.0)
(10850, 450.0)
(10885, 450.0)
(11071, 450.0)
(10903, 442.05)
(10943, 441.0)
(10858, 439.0)
(10974, 439.0)
(10826, 437.5)
(10443, 436.79999999999995)
(10296, 432.0)
(10559, 432.0)
(10906, 427.5)
(10958, 427.0)
(10956, 424.0)
(10326, 422.40000000000003)
(10376, 420.0)
(10498, 420.0)
(10502, 420.0)
(10651, 420.0)
(10797, 420.0)
(10813, 420.0)
(10919, 418.79999999999995)
(10576, 408.45)
(10676, 408.45)
(10300, 408.0)
(10512, 408.0)
(10532, 408.0)
(10927, 405.0)
(10365, 403.20000000000005)
(10254, 403.2)
(10367, 403.2)
(10405, 400.0)
(10695, 400.0)
(10763, 400.0)
(10882, 400.0)
(10952, 400.0)
(10610, 399.0)
(10594, 397.5)
(10341, 396.0)
(10354, 396.0)
(10307, 394.0)
(10394, 394.0)
(10256, 393.0)
(10437, 393.0)
(10483, 392.0)
(10571, 392.0)
(10355, 390.0)
(10597, 390.0)
(10915, 390.0)
(10916, 390.0)
(10920, 390.0)
(10891, 388.35)
(11015, 388.35)
(10581, 387.5)
(10592, 387.5)
(10951, 387.5)
(10280, 384.0)
(10622, 380.0)
(10806, 380.0)
(10856, 380.0)
(10888, 380.0)
(10720, 378.0)
(10935, 378.0)
(10444, 373.5)
(10591, 372.5)
(10276, 372.0)
(10291, 372.0)
(10412, 372.0)
(10716, 371.0)
(10500, 364.8)
(10937, 364.8)
(10266, 364.79999999999995)
(10262, 360.0)
(10315, 360.0)
(10529, 360.0)
(10578, 360.0)
(10587, 360.0)
(10647, 360.0)
(10654, 360.0)
(10732, 360.0)
(10821, 360.0)
(10860, 360.0)
(10863, 360.0)
(10905, 360.0)
(10909, 360.0)
(11069, 360.0)
(11075, 360.0)
(10794, 348.75)
(10798, 348.0)
(10926, 348.0)
(10274, 344.0)
(10771, 344.0)
(11009, 342.0)
(10625, 340.0)
(10917, 340.0)
(10251, 336.0)
(10456, 336.0)
(10743, 336.0)
(11062, 328.0)
(10621, 322.5)
(10819, 322.0)
(10759, 320.0)
(10544, 319.2)
(10336, 316.8)
(10542, 315.0)
(10648, 315.0)
(10770, 315.0)
(10842, 315.0)
(10528, 313.2)
(10416, 312.0)
(10550, 312.0)
(10832, 311.2)
(10609, 310.0)
(10613, 310.0)
(10785, 310.0)
(10874, 310.0)
(10980, 310.0)
(10704, 306.0)
(10358, 304.0)
(11016, 304.0)
(10374, 300.0)
(10453, 300.0)
(10875, 300.0)
(10448, 294.0)
(10614, 294.0)
(11042, 291.75)
(10261, 288.0)
(10317, 288.0)
(10425, 288.0)
(10477, 288.0)
(10493, 288.0)
(10741, 285.0)
(10652, 280.0)
(10777, 280.0)
(10970, 280.0)
(11054, 280.0)
(10375, 279.0)
(10435, 278.0)
(10454, 278.0)
(10673, 276.0)
(11014, 270.2)
(10702, 270.0)
(10275, 264.0)
(10306, 262.0)
(10730, 261.75)
(10434, 259.2)
(10534, 258.9)
(10489, 252.0)
(10506, 252.0)
(10582, 252.0)
(10705, 250.0)
(10432, 249.0)
(11006, 247.58)
(11074, 244.29999999999998)
(10289, 240.0)
(10299, 240.0)
(10940, 240.0)
(10438, 234.0)
(10577, 234.0)
(10972, 234.0)
(11034, 233.39999999999998)
(10491, 232.5)
(10682, 232.5)
(10998, 232.5)
(10960, 231.60000000000002)
(10409, 223.20000000000002)
(10879, 220.79999999999998)
(10517, 220.0)
(10947, 220.0)
(10348, 216.0)
(10843, 212.0)
(10460, 210.0)
(10545, 210.0)
(10864, 210.0)
(11043, 210.0)
(11073, 210.0)
(10473, 206.39999999999998)
(10311, 201.6)
(10363, 200.0)
(10496, 200.0)
(10873, 200.0)
(10910, 200.0)
(11040, 200.0)
(10310, 197.0)
(10655, 193.0)
(10428, 192.0)
(10792, 190.0)
(11013, 190.0)
(11049, 190.0)
(11004, 187.38)
(10426, 186.20000000000002)
(10775, 186.0)
(11003, 184.0)
(10313, 182.39999999999998)
(10508, 180.0)
(10604, 180.0)
(10840, 180.0)
(11025, 180.0)
(10248, 174.0)
(10466, 168.0)
(10520, 164.0)
(10579, 162.75)
(10973, 156.15)
(10568, 155.0)
(10959, 155.0)
(10318, 154.0)
(10495, 154.0)
(10462, 151.20000000000002)
(10539, 150.0)
(10881, 150.0)
(10501, 149.0)
(11065, 149.0)
(10505, 147.89999999999998)
(10822, 147.89999999999998)
(10482, 147.0)
(10484, 147.0)
(10321, 144.0)
(10476, 144.0)
(10725, 144.0)
(10752, 144.0)
(10899, 144.0)
(10585, 142.5)
(10349, 141.60000000000002)
(10548, 140.0)
(10809, 140.0)
(10509, 136.8)
(11060, 136.0)
(10793, 135.1)
(10824, 135.0)
(10467, 134.39999999999998)
(10414, 131.4)
(10739, 126.0)
(10662, 125.0)
(10945, 125.0)
(10282, 124.19999999999999)
(10295, 121.6)
(10615, 120.0)
(10352, 118.0)
(10737, 115.80000000000001)
(10699, 114.0)
(10322, 112.0)
(10381, 112.0)
(10386, 112.0)
(10531, 110.0)
(10950, 110.0)
(10907, 108.5)
(10969, 108.0)
(10870, 106.0)
(10538, 105.0)
(10378, 103.19999999999999)
(10334, 100.0)
(10867, 98.39999999999999)
(10521, 96.5)
(10778, 96.5)
(10708, 95.0)
(10955, 93.0)
(10371, 91.19999999999999)
(10928, 90.0)
(10331, 88.5)
(10445, 88.5)
(10446, 87.6)
(11067, 86.85000000000001)
(10391, 86.39999999999999)
(10366, 84.0)
(10259, 80.0)
(10810, 75.0)
(10589, 72.0)
(10887, 70.0)
(10992, 69.6)
(10963, 68.0)
(10602, 65.0)
(10683, 63.0)
(10415, 62.4)
(10323, 62.0)
(10631, 62.0)
(10308, 60.0)
(11037, 60.0)
(10288, 59.0)
(10281, 57.6)
(10754, 55.199999999999996)
(10738, 52.349999999999994)
(10753, 50.0)
(10422, 49.8)
(10271, 48.0)
(10710, 47.5)
(10674, 45.0)
(10900, 45.0)
(11051, 45.0)
(11057, 45.0)
(10815, 40.0)
(11019, 40.0)
(10883, 36.0)
(10620, 35.0)
(10898, 30.0)
(10586, 28.0)
(10767, 28.0)
(10807, 18.4)
(10782, 12.5)

In [7]:
    # Extraed el n√∫meros de pedidos que se hayan hecho por dia. Devuelve los resultados en una dataframe.

import mysql.connector
import pandas as pd


cnx = mysql.connector.connect(user='root', password='AlumnaAdalab',
                              host='127.0.0.1',
                              database='northwind')

print(cnx)
mycursor = cnx.cursor()
mycursor.execute("SELECT COUNT(order_id), DAY(order_date), MONTH(order_date), YEAR(order_date) FROM orders")
myresult = mycursor.fetchall()

df = pd.DataFrame(myresult, columns = ['Cantidad de Pedidos', 'Fecha'])
print(df)


# Tengo problemas con el m√≥dulo de pandas. Por eso da error.

ModuleNotFoundError: No module named 'pandas'

In [8]:
    #Extraer los pedidos hechos por "Nancy Daviolo". Tendr√©is que hacer una subquery.

mydb = mysql.connector.connect(
                  user='root', password='AlumnaAdalab',
                  host='127.0.0.1',
                  database='Northwind')

mycursor = mydb.cursor()

mycursor.execute("SELECT * FROM orders WHERE employee_id IN (SELECT employee_id FROM employees WHERE first_name = 'Nancy' AND last_name = 'Davolio')")


for x in mycursor:
 print(x)

(10258, 'ERNSH', 1, datetime.datetime(1996, 7, 17, 0, 0), datetime.datetime(1996, 8, 14, 0, 0), datetime.datetime(1996, 7, 23, 0, 0), 1, 140.51, 'Ernst Handel', 'Kirchgasse 6', 'Graz', '', '8010', 'Austria')
(10270, 'WARTH', 1, datetime.datetime(1996, 8, 1, 0, 0), datetime.datetime(1996, 8, 29, 0, 0), datetime.datetime(1996, 8, 2, 0, 0), 1, 136.54, 'Wartian Herkku', 'Torikatu 38', 'Oulu', '', '90110', 'Finland')
(10275, 'MAGAA', 1, datetime.datetime(1996, 8, 7, 0, 0), datetime.datetime(1996, 9, 4, 0, 0), datetime.datetime(1996, 8, 9, 0, 0), 1, 26.93, 'Magazzini Alimentari Riuniti', 'Via Ludovico il Moro 22', 'Bergamo', '', '24100', 'Italy')
(10285, 'QUICK', 1, datetime.datetime(1996, 8, 20, 0, 0), datetime.datetime(1996, 9, 17, 0, 0), datetime.datetime(1996, 8, 26, 0, 0), 2, 76.83, 'QUICK-Stop', 'TaucherstraÔøΩe 10', 'Cunewalde', '', '1307', 'Germany')
(10292, 'TRADH', 1, datetime.datetime(1996, 8, 28, 0, 0), datetime.datetime(1996, 9, 25, 0, 0), datetime.datetime(1996, 9, 2, 0, 0), 2, 1.35, 'TradiÔøΩao Hipermercados', 'Av. InÔøΩs de Castro, 414', 'Sao Paulo', 'SP', '05634-030', 'Brazil')
(10293, 'TORTU', 1, datetime.datetime(1996, 8, 29, 0, 0), datetime.datetime(1996, 9, 26, 0, 0), datetime.datetime(1996, 9, 11, 0, 0), 3, 21.18, 'Tortuga Restaurante', 'Avda. Azteca 123', 'MÔøΩxico D.F.', '', '5033', 'Mexico')
(10304, 'TORTU', 1, datetime.datetime(1996, 9, 12, 0, 0), datetime.datetime(1996, 10, 10, 0, 0), datetime.datetime(1996, 9, 17, 0, 0), 2, 63.79, 'Tortuga Restaurante', 'Avda. Azteca 123', 'MÔøΩxico D.F.', '', '5033', 'Mexico')
(10306, 'ROMEY', 1, datetime.datetime(1996, 9, 16, 0, 0), datetime.datetime(1996, 10, 14, 0, 0), datetime.datetime(1996, 9, 23, 0, 0), 3, 7.56, 'Romero y tomillo', 'Gran VÔøΩa, 1', 'Madrid', '', '28001', 'Spain')
(10311, 'DUMON', 1, datetime.datetime(1996, 9, 20, 0, 0), datetime.datetime(1996, 10, 4, 0, 0), datetime.datetime(1996, 9, 26, 0, 0), 3, 24.69, 'Du monde entier', '67, rue des Cinquante Otages', 'Nantes', '', '44000', 'France')
(10314, 'RATTC', 1, datetime.datetime(1996, 9, 25, 0, 0), datetime.datetime(1996, 10, 23, 0, 0), datetime.datetime(1996, 10, 4, 0, 0), 2, 74.16, 'Rattlesnake Canyon Grocery', '2817 Milton Dr.', 'Albuquerque', 'NM', '87110', 'USA')
(10316, 'RATTC', 1, datetime.datetime(1996, 9, 27, 0, 0), datetime.datetime(1996, 10, 25, 0, 0), datetime.datetime(1996, 10, 8, 0, 0), 3, 150.15, 'Rattlesnake Canyon Grocery', '2817 Milton Dr.', 'Albuquerque', 'NM', '87110', 'USA')
(10325, 'KOENE', 1, datetime.datetime(1996, 10, 9, 0, 0), datetime.datetime(1996, 10, 23, 0, 0), datetime.datetime(1996, 10, 14, 0, 0), 3, 64.86, 'KÔøΩniglich Essen', 'Maubelstr. 90', 'Brandenburg', '', '14776', 'Germany')
(10340, 'BONAP', 1, datetime.datetime(1996, 10, 29, 0, 0), datetime.datetime(1996, 11, 26, 0, 0), datetime.datetime(1996, 11, 8, 0, 0), 3, 166.31, "Bon app'", '12, rue des Bouchers', 'Marseille', '', '13008', 'France')
(10351, 'ERNSH', 1, datetime.datetime(1996, 11, 11, 0, 0), datetime.datetime(1996, 12, 9, 0, 0), datetime.datetime(1996, 11, 20, 0, 0), 1, 162.33, 'Ernst Handel', 'Kirchgasse 6', 'Graz', '', '8010', 'Austria')
(10357, 'LILAS', 1, datetime.datetime(1996, 11, 19, 0, 0), datetime.datetime(1996, 12, 17, 0, 0), datetime.datetime(1996, 12, 2, 0, 0), 3, 34.88, 'LILA-Supermercado', 'Carrera 52 con Ave. BolÔøΩvar #65-98 Llano Largo', 'Barquisimeto', 'Lara', '3508', 'Venezuela')
(10361, 'QUICK', 1, datetime.datetime(1996, 11, 22, 0, 0), datetime.datetime(1996, 12, 20, 0, 0), datetime.datetime(1996, 12, 3, 0, 0), 2, 183.17, 'QUICK-Stop', 'TaucherstraÔøΩe 10', 'Cunewalde', '', '1307', 'Germany')
(10364, 'EASTC', 1, datetime.datetime(1996, 11, 26, 0, 0), datetime.datetime(1997, 1, 7, 0, 0), datetime.datetime(1996, 12, 4, 0, 0), 1, 71.97, 'Eastern Connection', '35 King George', 'London', '', 'WX3 6FW', 'UK')
(10371, 'LAMAI', 1, datetime.datetime(1996, 12, 3, 0, 0), datetime.datetime(1996, 12, 31, 0, 0), datetime.datetime(1996, 12, 24, 0, 0), 1, 0.45, "La maison d'Asie", '1 rue Alsace-Lorraine', 'Toulouse', '', '31000', 'France')
(10374, 'WOLZA', 1, datetime.datetime(1996, 12, 5, 0, 0), datetime.datetime(1997, 1, 2, 0, 0), datetime.datetime(1996, 12, 9, 0, 0), 3, 3.94, 'Wolski Zajazd', 'ul. Filtrowa 68', 'Warszawa', '', '01-012', 'Poland')
(10376, 'MEREP', 1, datetime.datetime(1996, 12, 9, 0, 0), datetime.datetime(1997, 1, 6, 0, 0), datetime.datetime(1996, 12, 13, 0, 0), 2, 20.39, 'MÔøΩre Paillarde', '43 rue St. Laurent', 'MontrÔøΩal', 'QuÔøΩbec', 'H1J 1C3', 'Canada')
(10377, 'SEVES', 1, datetime.datetime(1996, 12, 9, 0, 0), datetime.datetime(1997, 1, 6, 0, 0), datetime.datetime(1996, 12, 13, 0, 0), 3, 22.21, 'Seven Seas Imports', '90 Wadhurst Rd.', 'London', '', 'OX15 4NB', 'UK')
(10385, 'SPLIR', 1, datetime.datetime(1996, 12, 17, 0, 0), datetime.datetime(1997, 1, 14, 0, 0), datetime.datetime(1996, 12, 23, 0, 0), 2, 30.96, 'Split Rail Beer & Ale', 'P.O. Box 555', 'Lander', 'WY', '82520', 'USA')
(10387, 'SANTG', 1, datetime.datetime(1996, 12, 18, 0, 0), datetime.datetime(1997, 1, 15, 0, 0), datetime.datetime(1996, 12, 20, 0, 0), 2, 93.63, 'SantÔøΩ Gourmet', 'Erling Skakkes gate 78', 'Stavern', '', '4110', 'Norway')
(10393, 'SAVEA', 1, datetime.datetime(1996, 12, 25, 0, 0), datetime.datetime(1997, 1, 22, 0, 0), datetime.datetime(1997, 1, 3, 0, 0), 3, 126.56, 'Save-a-lot Markets', '187 Suffolk Ln.', 'Boise', 'ID', '83720', 'USA')
(10394, 'HUNGC', 1, datetime.datetime(1996, 12, 25, 0, 0), datetime.datetime(1997, 1, 22, 0, 0), datetime.datetime(1997, 1, 3, 0, 0), 3, 30.34, 'Hungry Coyote Import Store', 'City Center Plaza 516 Main St.', 'Elgin', 'OR', '97827', 'USA')
(10396, 'FRANK', 1, datetime.datetime(1996, 12, 27, 0, 0), datetime.datetime(1997, 1, 10, 0, 0), datetime.datetime(1997, 1, 6, 0, 0), 3, 135.35, 'Frankenversand', 'Berliner Platz 43', 'MÔøΩnchen', '', '80805', 'Germany')
(10400, 'EASTC', 1, datetime.datetime(1997, 1, 1, 0, 0), datetime.datetime(1997, 1, 29, 0, 0), datetime.datetime(1997, 1, 16, 0, 0), 3, 83.93, 'Eastern Connection', '35 King George', 'London', '', 'WX3 6FW', 'UK')
(10401, 'RATTC', 1, datetime.datetime(1997, 1, 1, 0, 0), datetime.datetime(1997, 1, 29, 0, 0), datetime.datetime(1997, 1, 10, 0, 0), 1, 12.51, 'Rattlesnake Canyon Grocery', '2817 Milton Dr.', 'Albuquerque', 'NM', '87110', 'USA')
(10405, 'LINOD', 1, datetime.datetime(1997, 1, 6, 0, 0), datetime.datetime(1997, 2, 3, 0, 0), datetime.datetime(1997, 1, 22, 0, 0), 1, 34.82, 'LINO-Delicateses', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', 'Nueva Esparta', '4980', 'Venezuela')
(10453, 'AROUT', 1, datetime.datetime(1997, 2, 21, 0, 0), datetime.datetime(1997, 3, 21, 0, 0), datetime.datetime(1997, 2, 26, 0, 0), 2, 25.36, 'Around the Horn', 'Brook Farm Stratford St. Mary', 'Colchester', 'Essex', 'CO7 6JX', 'UK')
(10461, 'LILAS', 1, datetime.datetime(1997, 2, 28, 0, 0), datetime.datetime(1997, 3, 28, 0, 0), datetime.datetime(1997, 3, 5, 0, 0), 3, 148.61, 'LILA-Supermercado', 'Carrera 52 con Ave. BolÔøΩvar #65-98 Llano Largo', 'Barquisimeto', 'Lara', '3508', 'Venezuela')
(10465, 'VAFFE', 1, datetime.datetime(1997, 3, 5, 0, 0), datetime.datetime(1997, 4, 2, 0, 0), datetime.datetime(1997, 3, 14, 0, 0), 3, 145.04, 'Vaffeljernet', 'Smagsloget 45', 'ÔøΩrhus', '', '8200', 'Denmark')
(10469, 'WHITC', 1, datetime.datetime(1997, 3, 10, 0, 0), datetime.datetime(1997, 4, 7, 0, 0), datetime.datetime(1997, 3, 14, 0, 0), 1, 60.18, 'White Clover Markets', '1029 - 12th Ave. S.', 'Seattle', 'WA', '98124', 'USA')
(10473, 'ISLAT', 1, datetime.datetime(1997, 3, 13, 0, 0), datetime.datetime(1997, 3, 27, 0, 0), datetime.datetime(1997, 3, 21, 0, 0), 3, 16.37, 'Island Trading', 'Garden House Crowther Way', 'Cowes', 'Isle of Wight', 'PO31 7PJ', 'UK')
(10482, 'LAZYK', 1, datetime.datetime(1997, 3, 21, 0, 0), datetime.datetime(1997, 4, 18, 0, 0), datetime.datetime(1997, 4, 10, 0, 0), 3, 7.48, 'Lazy K Kountry Store', '12 Orchestra Terrace', 'Walla Walla', 'WA', '99362', 'USA')
(10486, 'HILAA', 1, datetime.datetime(1997, 3, 26, 0, 0), datetime.datetime(1997, 4, 23, 0, 0), datetime.datetime(1997, 4, 2, 0, 0), 2, 30.53, 'HILARION-Abastos', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San CristÔøΩbal', 'TÔøΩchira', '5022', 'Venezuela')
(10508, 'OTTIK', 1, datetime.datetime(1997, 4, 16, 0, 0), datetime.datetime(1997, 5, 14, 0, 0), datetime.datetime(1997, 5, 13, 0, 0), 2, 4.99, 'Ottilies KÔøΩseladen', 'Mehrheimerstr. 369', 'KÔøΩln', '', '50739', 'Germany')
(10524, 'BERGS', 1, datetime.datetime(1997, 5, 1, 0, 0), datetime.datetime(1997, 5, 29, 0, 0), datetime.datetime(1997, 5, 7, 0, 0), 2, 244.79, 'Berglunds snabbkÔøΩp', 'BerguvsvÔøΩgen  8', 'LuleÔøΩ', '', 'S-958 22', 'Sweden')
(10525, 'BONAP', 1, datetime.datetime(1997, 5, 2, 0, 0), datetime.datetime(1997, 5, 30, 0, 0), datetime.datetime(1997, 5, 23, 0, 0), 2, 11.06, "Bon app'", '12, rue des Bouchers', 'Marseille', '', '13008', 'France')
(10537, 'RICSU', 1, datetime.datetime(1997, 5, 14, 0, 0), datetime.datetime(1997, 5, 28, 0, 0), datetime.datetime(1997, 5, 19, 0, 0), 1, 78.85, 'Richter Supermarkt', 'Starenweg 5', 'GenÔøΩve', '', '1204', 'Switzerland')
(10542, 'KOENE', 1, datetime.datetime(1997, 5, 20, 0, 0), datetime.datetime(1997, 6, 17, 0, 0), datetime.datetime(1997, 5, 26, 0, 0), 3, 10.95, 'KÔøΩniglich Essen', 'Maubelstr. 90', 'Brandenburg', '', '14776', 'Germany')
(10546, 'VICTE', 1, datetime.datetime(1997, 5, 23, 0, 0), datetime.datetime(1997, 6, 20, 0, 0), datetime.datetime(1997, 5, 27, 0, 0), 3, 194.72, 'Victuailles en stock', '2, rue du Commerce', 'Lyon', '', '69004', 'France')
(10558, 'AROUT', 1, datetime.datetime(1997, 6, 4, 0, 0), datetime.datetime(1997, 7, 2, 0, 0), datetime.datetime(1997, 6, 10, 0, 0), 2, 72.97, 'Around the Horn', 'Brook Farm Stratford St. Mary', 'Colchester', 'Essex', 'CO7 6JX', 'UK')
(10562, 'REGGC', 1, datetime.datetime(1997, 6, 9, 0, 0), datetime.datetime(1997, 7, 7, 0, 0), datetime.datetime(1997, 6, 12, 0, 0), 1, 22.95, 'Reggiani Caseifici', 'Strada Provinciale 124', 'Reggio Emilia', '', '42100', 'Italy')
(10567, 'HUNGO', 1, datetime.datetime(1997, 6, 12, 0, 0), datetime.datetime(1997, 7, 10, 0, 0), datetime.datetime(1997, 6, 17, 0, 0), 1, 33.97, 'Hungry Owl All-Night Grocers', '8 Johnstown Road', 'Cork', 'Co. Cork', '', 'Ireland')
(10579, 'LETSS', 1, datetime.datetime(1997, 6, 25, 0, 0), datetime.datetime(1997, 7, 23, 0, 0), datetime.datetime(1997, 7, 4, 0, 0), 2, 13.73, "Let's Stop N Shop", '87 Polk St. Suite 5', 'San Francisco', 'CA', '94117', 'USA')
(10587, 'QUEDE', 1, datetime.datetime(1997, 7, 2, 0, 0), datetime.datetime(1997, 7, 30, 0, 0), datetime.datetime(1997, 7, 9, 0, 0), 1, 62.52, 'Que DelÔøΩcia', 'Rua da Panificadora, 12', 'Rio de Janeiro', 'RJ', '02389-673', 'Brazil')
(10591, 'VAFFE', 1, datetime.datetime(1997, 7, 7, 0, 0), datetime.datetime(1997, 7, 21, 0, 0), datetime.datetime(1997, 7, 16, 0, 0), 1, 55.92, 'Vaffeljernet', 'Smagsloget 45', 'ÔøΩrhus', '', '8200', 'Denmark')
(10598, 'RATTC', 1, datetime.datetime(1997, 7, 14, 0, 0), datetime.datetime(1997, 8, 11, 0, 0), datetime.datetime(1997, 7, 18, 0, 0), 3, 44.42, 'Rattlesnake Canyon Grocery', '2817 Milton Dr.', 'Albuquerque', 'NM', '87110', 'USA')
(10604, 'FURIB', 1, datetime.datetime(1997, 7, 18, 0, 0), datetime.datetime(1997, 8, 15, 0, 0), datetime.datetime(1997, 7, 29, 0, 0), 1, 7.46, 'Furia Bacalhau e Frutos do Mar', 'Jardim das rosas n. 32', 'Lisboa', '', '1675', 'Portugal')
(10605, 'MEREP', 1, datetime.datetime(1997, 7, 21, 0, 0), datetime.datetime(1997, 8, 18, 0, 0), datetime.datetime(1997, 7, 29, 0, 0), 2, 379.13, 'MÔøΩre Paillarde', '43 rue St. Laurent', 'MontrÔøΩal', 'QuÔøΩbec', 'H1J 1C3', 'Canada')
(10612, 'SAVEA', 1, datetime.datetime(1997, 7, 28, 0, 0), datetime.datetime(1997, 8, 25, 0, 0), datetime.datetime(1997, 8, 1, 0, 0), 2, 544.08, 'Save-a-lot Markets', '187 Suffolk Ln.', 'Boise', 'ID', '83720', 'USA')
(10616, 'GREAL', 1, datetime.datetime(1997, 7, 31, 0, 0), datetime.datetime(1997, 8, 28, 0, 0), datetime.datetime(1997, 8, 5, 0, 0), 2, 116.53, 'Great Lakes Food Market', '2732 Baker Blvd.', 'Eugene', 'OR', '97403', 'USA')
(10618, 'MEREP', 1, datetime.datetime(1997, 8, 1, 0, 0), datetime.datetime(1997, 9, 12, 0, 0), datetime.datetime(1997, 8, 8, 0, 0), 1, 154.68, 'MÔøΩre Paillarde', '43 rue St. Laurent', 'MontrÔøΩal', 'QuÔøΩbec', 'H1J 1C3', 'Canada')
(10626, 'BERGS', 1, datetime.datetime(1997, 8, 11, 0, 0), datetime.datetime(1997, 9, 8, 0, 0), datetime.datetime(1997, 8, 20, 0, 0), 2, 138.69, 'Berglunds snabbkÔøΩp', 'BerguvsvÔøΩgen  8', 'LuleÔøΩ', '', 'S-958 22', 'Sweden')
(10630, 'KOENE', 1, datetime.datetime(1997, 8, 13, 0, 0), datetime.datetime(1997, 9, 10, 0, 0), datetime.datetime(1997, 8, 19, 0, 0), 2, 32.35, 'KÔøΩniglich Essen', 'Maubelstr. 90', 'Brandenburg', '', '14776', 'Germany')
(10653, 'FRANK', 1, datetime.datetime(1997, 9, 2, 0, 0), datetime.datetime(1997, 9, 30, 0, 0), datetime.datetime(1997, 9, 19, 0, 0), 1, 93.25, 'Frankenversand', 'Berliner Platz 43', 'MÔøΩnchen', '', '80805', 'Germany')
(10655, 'REGGC', 1, datetime.datetime(1997, 9, 3, 0, 0), datetime.datetime(1997, 10, 1, 0, 0), datetime.datetime(1997, 9, 11, 0, 0), 2, 4.41, 'Reggiani Caseifici', 'Strada Provinciale 124', 'Reggio Emilia', '', '42100', 'Italy')
(10664, 'FURIB', 1, datetime.datetime(1997, 9, 10, 0, 0), datetime.datetime(1997, 10, 8, 0, 0), datetime.datetime(1997, 9, 19, 0, 0), 3, 1.27, 'Furia Bacalhau e Frutos do Mar', 'Jardim das rosas n. 32', 'Lisboa', '', '1675', 'Portugal')
(10665, 'LONEP', 1, datetime.datetime(1997, 9, 11, 0, 0), datetime.datetime(1997, 10, 9, 0, 0), datetime.datetime(1997, 9, 17, 0, 0), 2, 26.31, 'Lonesome Pine Restaurant', '89 Chiaroscuro Rd.', 'Portland', 'OR', '97219', 'USA')
(10668, 'WANDK', 1, datetime.datetime(1997, 9, 15, 0, 0), datetime.datetime(1997, 10, 13, 0, 0), datetime.datetime(1997, 9, 23, 0, 0), 2, 47.22, 'Die Wandernde Kuh', 'Adenauerallee 900', 'Stuttgart', '', '70563', 'Germany')
(10671, 'FRANR', 1, datetime.datetime(1997, 9, 17, 0, 0), datetime.datetime(1997, 10, 15, 0, 0), datetime.datetime(1997, 9, 24, 0, 0), 1, 30.34, 'France restauration', '54, rue Royale', 'Nantes', '', '44000', 'France')
(10677, 'ANTON', 1, datetime.datetime(1997, 9, 22, 0, 0), datetime.datetime(1997, 10, 20, 0, 0), datetime.datetime(1997, 9, 26, 0, 0), 3, 4.03, 'Antonio Moreno TaquerÔøΩa', 'Mataderos  2312', 'MÔøΩxico D.F.', '', '5023', 'Mexico')
(10680, 'OLDWO', 1, datetime.datetime(1997, 9, 24, 0, 0), datetime.datetime(1997, 10, 22, 0, 0), datetime.datetime(1997, 9, 26, 0, 0), 1, 26.61, 'Old World Delicatessen', '2743 Bering St.', 'Anchorage', 'AK', '99508', 'USA')
(10689, 'BERGS', 1, datetime.datetime(1997, 10, 1, 0, 0), datetime.datetime(1997, 10, 29, 0, 0), datetime.datetime(1997, 10, 7, 0, 0), 2, 13.42, 'Berglunds snabbkÔøΩp', 'BerguvsvÔøΩgen  8', 'LuleÔøΩ', '', 'S-958 22', 'Sweden')
(10690, 'HANAR', 1, datetime.datetime(1997, 10, 2, 0, 0), datetime.datetime(1997, 10, 30, 0, 0), datetime.datetime(1997, 10, 3, 0, 0), 1, 15.8, 'Hanari Carnes', 'Rua do PaÔøΩo, 67', 'Rio de Janeiro', 'RJ', '05454-876', 'Brazil')
(10709, 'GOURL', 1, datetime.datetime(1997, 10, 17, 0, 0), datetime.datetime(1997, 11, 14, 0, 0), datetime.datetime(1997, 11, 20, 0, 0), 3, 210.8, 'Gourmet Lanchonetes', 'Av. Brasil, 442', 'Campinas', 'SP', '04876-786', 'Brazil')
(10710, 'FRANS', 1, datetime.datetime(1997, 10, 20, 0, 0), datetime.datetime(1997, 11, 17, 0, 0), datetime.datetime(1997, 10, 23, 0, 0), 1, 4.98, 'Franchi S.p.A.', 'Via Monte Bianco 34', 'Torino', '', '10100', 'Italy')
(10713, 'SAVEA', 1, datetime.datetime(1997, 10, 22, 0, 0), datetime.datetime(1997, 11, 19, 0, 0), datetime.datetime(1997, 10, 24, 0, 0), 1, 167.05, 'Save-a-lot Markets', '187 Suffolk Ln.', 'Boise', 'ID', '83720', 'USA')
(10717, 'FRANK', 1, datetime.datetime(1997, 10, 24, 0, 0), datetime.datetime(1997, 11, 21, 0, 0), datetime.datetime(1997, 10, 29, 0, 0), 2, 59.25, 'Frankenversand', 'Berliner Platz 43', 'MÔøΩnchen', '', '80805', 'Germany')
(10718, 'KOENE', 1, datetime.datetime(1997, 10, 27, 0, 0), datetime.datetime(1997, 11, 24, 0, 0), datetime.datetime(1997, 10, 29, 0, 0), 3, 170.88, 'KÔøΩniglich Essen', 'Maubelstr. 90', 'Brandenburg', '', '14776', 'Germany')
(10733, 'BERGS', 1, datetime.datetime(1997, 11, 7, 0, 0), datetime.datetime(1997, 12, 5, 0, 0), datetime.datetime(1997, 11, 10, 0, 0), 3, 110.11, 'Berglunds snabbkÔøΩp', 'BerguvsvÔøΩgen  8', 'LuleÔøΩ', '', 'S-958 22', 'Sweden')
(10743, 'AROUT', 1, datetime.datetime(1997, 11, 17, 0, 0), datetime.datetime(1997, 12, 15, 0, 0), datetime.datetime(1997, 11, 21, 0, 0), 2, 23.72, 'Around the Horn', 'Brook Farm Stratford St. Mary', 'Colchester', 'Essex', 'CO7 6JX', 'UK')
(10746, 'CHOPS', 1, datetime.datetime(1997, 11, 19, 0, 0), datetime.datetime(1997, 12, 17, 0, 0), datetime.datetime(1997, 11, 21, 0, 0), 3, 31.43, 'Chop-suey Chinese', 'Hauptstr. 31', 'Bern', '', '3012', 'Switzerland')
(10773, 'ERNSH', 1, datetime.datetime(1997, 12, 11, 0, 0), datetime.datetime(1998, 1, 8, 0, 0), datetime.datetime(1997, 12, 16, 0, 0), 3, 96.43, 'Ernst Handel', 'Kirchgasse 6', 'Graz', '', '8010', 'Austria')
(10776, 'ERNSH', 1, datetime.datetime(1997, 12, 15, 0, 0), datetime.datetime(1998, 1, 12, 0, 0), datetime.datetime(1997, 12, 18, 0, 0), 3, 351.53, 'Ernst Handel', 'Kirchgasse 6', 'Graz', '', '8010', 'Austria')
(10785, 'GROSR', 1, datetime.datetime(1997, 12, 18, 0, 0), datetime.datetime(1998, 1, 15, 0, 0), datetime.datetime(1997, 12, 24, 0, 0), 3, 1.51, 'GROSELLA-Restaurante', '5ÔøΩ Ave. Los Palos Grandes', 'Caracas', 'DF', '1081', 'Venezuela')
(10788, 'QUICK', 1, datetime.datetime(1997, 12, 22, 0, 0), datetime.datetime(1998, 1, 19, 0, 0), datetime.datetime(1998, 1, 19, 0, 0), 2, 42.7, 'QUICK-Stop', 'TaucherstraÔøΩe 10', 'Cunewalde', '', '1307', 'Germany')
(10789, 'FOLIG', 1, datetime.datetime(1997, 12, 22, 0, 0), datetime.datetime(1998, 1, 19, 0, 0), datetime.datetime(1997, 12, 31, 0, 0), 2, 100.6, 'Folies gourmandes', '184, chaussÔøΩe de Tournai', 'Lille', '', '59000', 'France')
(10792, 'WOLZA', 1, datetime.datetime(1997, 12, 23, 0, 0), datetime.datetime(1998, 1, 20, 0, 0), datetime.datetime(1997, 12, 31, 0, 0), 3, 23.79, 'Wolski Zajazd', 'ul. Filtrowa 68', 'Warszawa', '', '01-012', 'Poland')
(10800, 'SEVES', 1, datetime.datetime(1997, 12, 26, 0, 0), datetime.datetime(1998, 1, 23, 0, 0), datetime.datetime(1998, 1, 5, 0, 0), 3, 137.44, 'Seven Seas Imports', '90 Wadhurst Rd.', 'London', '', 'OX15 4NB', 'UK')
(10813, 'RICAR', 1, datetime.datetime(1998, 1, 5, 0, 0), datetime.datetime(1998, 2, 2, 0, 0), datetime.datetime(1998, 1, 9, 0, 0), 1, 47.38, 'Ricardo Adocicados', 'Av. Copacabana, 267', 'Rio de Janeiro', 'RJ', '02389-890', 'Brazil')
(10821, 'SPLIR', 1, datetime.datetime(1998, 1, 8, 0, 0), datetime.datetime(1998, 2, 5, 0, 0), datetime.datetime(1998, 1, 15, 0, 0), 1, 36.68, 'Split Rail Beer & Ale', 'P.O. Box 555', 'Lander', 'WY', '82520', 'USA')
(10825, 'DRACD', 1, datetime.datetime(1998, 1, 9, 0, 0), datetime.datetime(1998, 2, 6, 0, 0), datetime.datetime(1998, 1, 14, 0, 0), 1, 79.25, 'Drachenblut Delikatessen', 'Walserweg 21', 'Aachen', '', '52066', 'Germany')
(10827, 'BONAP', 1, datetime.datetime(1998, 1, 12, 0, 0), datetime.datetime(1998, 1, 26, 0, 0), datetime.datetime(1998, 2, 6, 0, 0), 2, 63.54, "Bon app'", '12, rue des Bouchers', 'Marseille', '', '13008', 'France')
(10834, 'TRADH', 1, datetime.datetime(1998, 1, 15, 0, 0), datetime.datetime(1998, 2, 12, 0, 0), datetime.datetime(1998, 1, 19, 0, 0), 3, 29.78, 'TradiÔøΩao Hipermercados', 'Av. InÔøΩs de Castro, 414', 'Sao Paulo', 'SP', '05634-030', 'Brazil')
(10835, 'ALFKI', 1, datetime.datetime(1998, 1, 15, 0, 0), datetime.datetime(1998, 2, 12, 0, 0), datetime.datetime(1998, 1, 21, 0, 0), 3, 69.53, "Alfred's Futterkiste", 'Obere Str. 57', 'Berlin', '', '12209', 'Germany')
(10842, 'TORTU', 1, datetime.datetime(1998, 1, 20, 0, 0), datetime.datetime(1998, 2, 17, 0, 0), datetime.datetime(1998, 1, 29, 0, 0), 3, 54.42, 'Tortuga Restaurante', 'Avda. Azteca 123', 'MÔøΩxico D.F.', '', '5033', 'Mexico')

In [9]:
# EJERCICIO 5:

# Para finalizar el ejercicio, desconectad la conexi√≥n con el servidor.

cnx.close()